"""Initial migration after resync

Revision ID: 78aad55db000
Revises: 
Create Date: 2025-05-14 14:23:23.623737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78aad55db000'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_user_inputs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_alembic_tmp_user_inputs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('exercise', sa.VARCHAR(length=10), nullable=True),
    sa.Column('exercise_hours', sa.FLOAT(), nullable=True),
    sa.Column('water_intake', sa.FLOAT(), nullable=True),
    sa.Column('sleep_hours', sa.FLOAT(), nullable=True),
    sa.Column('reading_hours', sa.FLOAT(), nullable=True),
    sa.Column('meals', sa.INTEGER(), nullable=True),
    sa.Column('screen_hours', sa.FLOAT(), nullable=True),
    sa.Column('productivity', sa.INTEGER(), nullable=True),
    sa.Column('mood', sa.VARCHAR(length=20), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_userinput_user_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='_user_date_uc')
    )
    # ### end Alembic commands ###
