"""Recreate user and user_inputs tables

Revision ID: 868c09ad2a1a
Revises: 3bdb896c02f8
Create Date: 2025-05-13 22:58:39.546585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '868c09ad2a1a'
down_revision = '3bdb896c02f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('user_inputs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('exercise', sa.String(length=10), nullable=True),
    sa.Column('exercise_hours', sa.Float(), nullable=True),
    sa.Column('water_intake', sa.Float(), nullable=True),
    sa.Column('sleep_hours', sa.Float(), nullable=True),
    sa.Column('reading_hours', sa.Float(), nullable=True),
    sa.Column('meals', sa.Integer(), nullable=True),
    sa.Column('screen_hours', sa.Float(), nullable=True),
    sa.Column('productivity', sa.Integer(), nullable=True),
    sa.Column('mood', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_userinput_user_id'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_inputs')
    op.drop_table('user')
    # ### end Alembic commands ###
