"""Make created_at nullable in shared_access

Revision ID: f4b1328c49f8
Revises: a4a681e9902f
Create Date: 2025-05-14 18:03:01.549008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4b1328c49f8'
down_revision = 'a4a681e9902f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shared_access', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shared_access', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
